name: di_step5
description: "DI Step 5 - Injectable with Automatic Registration"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^8.2.0
  injectable: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.9.0
  build_runner: ^2.10.0

flutter:
  uses-material-design: true